### ISSUE TITLE
Test Results (Android 6.0.1)

### ISSUE THREAD

**Issue by mohdali** [Perfare/Riru-Il2CppDumper#1]
Hi,

Just want to share the initial test results:

Android Version: 6.0.1 Marshmallow (64 bit game)
Unity Version: 2018.4.2f1

Log output:

> 07-04 16:29:31.147 13193 13199 I Perfare : hack thread: 13199
> 07-04 16:29:31.147 13193 13199 I Perfare : api level: 23
> 07-04 16:29:31.161 13193 13199 I Perfare : do_dlopen at: 0x7f86c18edc
> 07-04 16:29:40.054 13193 13367 I Perfare : Got il2cpp handle!
> 07-04 16:29:42.163 13193 13199 I Perfare : il2cpp_handle: 0x7f7a188ba8
> 07-04 16:29:42.167 13193 13199 I Perfare : typeDefinitionsCount: 19396
> 07-04 16:29:42.175 13193 13199 D Perfare : data start 7f66bc2000
> 07-04 16:29:42.175 13193 13199 D Perfare : data end 7f67507000
> 07-04 16:29:42.175 13193 13199 D Perfare : data start 7f67507000
> 07-04 16:29:42.175 13193 13199 D Perfare : data end 7f677ef000
> 07-04 16:29:42.206 13193 13199 I Perfare : il2cpp_addr: 7f624a8000
> 07-04 16:29:42.206 13193 13199 I Perfare : metadataregistration_addr: 0

After that the game just boots normally and no files are generated.

I set the parameters in game.h as below as per the comments, hope that's correct.

```
#define UnityVersion 2018.3.8f1
```

**Comment by Perfare** [comment]
Please give me the game name or store address.

**Comment by mohdali** [comment]
com.klab.captain283.global

**Comment by Perfare** [comment]
I updated the search logic and it should work now.

**Comment by mohdali** [comment]
Thanks!

It is working now. And I can see the logs finding the addresses.
However, I still can't find the file being created under /data/<game>/files/dump.cs
Do I need to change folder permissions?

> 07-05 19:45:04.118 10232 10243 I Perfare : hack thread: 10243
> 07-05 19:45:04.118 10232 10243 I Perfare : api level: 23
> 07-05 19:45:04.135 10232 10243 I Perfare : do_dlopen at: 0x7fb1536edc
> 07-05 19:45:15.634 10232 10604 I Perfare : Got il2cpp handle!
> 07-05 19:45:21.141 10232 10243 I Perfare : il2cpp_handle: 0x7f966fb1f8
> 07-05 19:45:21.145 10232 10243 I Perfare : typeDefinitionsCount: 19396
> 07-05 19:45:21.164 10232 10243 D Perfare : metadataregistration_rva: 4c989b0
> 07-05 19:45:21.164 10232 10243 I Perfare : il2cpp_addr: 7f8c5b3000
> 07-05 19:45:21.164 10232 10243 I Perfare : metadataregistration_addr: 7f9124b9b0
> 07-05 19:45:21.164 10232 10243 I Perfare : dumping...
> 07-05 19:45:25.160 10232 10243 I Perfare : write dump file
> 07-05 19:45:25.335 10232 10243 I Perfare : dump done!

**Comment by mohdali** [comment]
OK I found the file in this location instead:

/data/user/0/com.klab.captain283.global/files/dump.cs

Thanks a lot! Excellent effort.

**Comment by RevealedSoulEven** [comment]
How to use it? The zip says that it is not a magisk module

**Comment by mrvizine** [comment]
Revealed soul even do you mind helping me?
